/** Maps sidebar paths to RFID permission flags (PascalCase + camelCase checked in hasPermission). */
export const SIDEBAR_PERMISSION_BY_PATH = {
  '/analytics': null,
  '/label-stock': 'CanViewStock',
  '/stock': 'CanAddStock',
  '/stock-verification': 'CanStockVerification',
  '/create-label': 'CanDesignLabel',
  '/rfid-label': 'CanCreatePRNLabel',
  '/quotation': 'CanQuotation',
  '/create-invoice': 'CanInvoice',
  '/sample-in': 'CanSampleIn',
  '/sample-out': 'CanSampleOut',
  '/sample-out-list': 'CanSampleOut',
  '/reports': 'CanViewReports',
  '/stock-transfer': 'CanStockTransfer',
  '/order-list': 'CanOrderList',
  '/rfid-devices': 'CanScanToDesktop',
  '/upload-rfid': 'CanRFIDTagsSheetUpload',
  '/rfid-tags': 'CanRFIDTagList',
  '/tag-usage': 'CanRFIDTagsUsage',
  '/stock-tracking': 'CanViewStock',
  '/box-rfid': 'CanViewStock',
  '/create-masters': 'CanManageBranches',
  '/rfid-utility': null,
  '/profile-menu': null,
};
